"""Changed unique_id in vinted_items to BIGINT

Revision ID: ef798b8f1d0b
Revises: 8cc2c57e3d5d
Create Date: 2023-03-31 16:13:16.445123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef798b8f1d0b'
down_revision = '8cc2c57e3d5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_published_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['vinted_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_bot_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_published_items')
    # ### end Alembic commands ###
